'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Github, Linkedin, Mail, FileText, Compass, Code2, Network, Layers3, GraduationCap, Menu, X, MapPin, Sparkles } from 'lucide-react';
import { profile, navigation, experiences, projects, skills, education } from '@/lib/portfolio';
import ArtifactDisplay from './ArtifactDisplay';
function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={{ opacity: 1, y: reduced ? 0 : 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-35px' }} transition={{ duration: reduced ? 0 : 0.6 }}>{children}</motion.div>;
}
function SectionHeading({ number, title, subtitle }: { number: string; title: string; subtitle: string }) {
  return <div className="section-heading"><div><span className="eyebrow"><span className="chapter">{number}</span> {subtitle}</span><h2>{title}<span>.</span></h2></div><div className="heading-rule"><Sparkles size={15} /></div></div>;
}
function ProjectIllustration({ archive }: { archive: boolean }) {
  return <div className={`project-art ${archive ? 'archive' : ''}`} aria-hidden="true"><svg viewBox="0 0 520 230" fill="none"><defs><radialGradient id={archive ? 'archiveGlow' : 'nodeGlow'}><stop stopColor={archive ? '#788eaa' : '#a5b79b'} stopOpacity=".2"/><stop offset="1" stopColor="#0c1318" stopOpacity="0"/></radialGradient></defs><ellipse cx="260" cy="115" rx="220" ry="130" fill={`url(#${archive ? 'archiveGlow' : 'nodeGlow'})`} />
  <g stroke="#81908b" strokeOpacity=".18"><ellipse cx="260" cy="115" rx="174" ry="74"/><ellipse cx="260" cy="115" rx="136" ry="98"/><path d="M55 115H465M260 12V217" strokeDasharray="3 7"/></g>
  {archive ? <g stroke="#8ea9bd"><path d="m176 69 84-33 84 33v105l-84 31-84-31V69Z" strokeOpacity=".4"/><path d="m176 69 84 32 84-32M260 101v104" strokeOpacity=".5"/><path d="m205 79 55-22 55 22-55 21-55-21ZM205 100v48l55 22 55-22v-48M205 119l55 22 55-22M205 138l55 22 55-22" strokeOpacity=".65"/><path d="m224 94 36-13 36 13M224 110l36 13 36-13" stroke="#d2d8bf"/><circle cx="260" cy="36" r="3" fill="#c7dbe1"/><circle cx="260" cy="205" r="3" fill="#c7dbe1"/><path d="M140 96v45M130 106v25M380 96v45M390 106v25" strokeOpacity=".4"/></g> : <g stroke="#b9c3a5"><path d="m140 119 65-58 64 51 65-62 56 85-92 45-29-68-76 63-53-56ZM205 61l-12 114 105 5 36-130M140 119l129-7 121 23" strokeOpacity=".45"/>{[[140,119],[205,61],[269,112],[334,50],[390,135],[298,180],[193,175]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r={i===2?16:9} strokeOpacity=".3"/><circle cx={x} cy={y} r={i===2?5:3} fill="#c9d5ba"/><circle cx={x} cy={y} r={i===2?24:15} strokeOpacity=".1"/></g>)}</g>}
  {[ [73,43], [411,57], [111,187], [443,175], [310,21], [57,142] ].map(([x,y],i)=><path key={i} d={`M${x-3} ${y}h6m-3-3v6`} stroke="#b4b39b" strokeOpacity=".45"/>)}</svg><span className="art-coordinate">{archive ? 'ARCHIVE / 002' : 'CONSTELLATION / 001'}</span></div>;
}
export default function Portfolio() {
  const [active, setActive] = useState('');
  const [menu, setMenu] = useState(false);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { for (const entry of entries) if (entry.isIntersecting) setActive(entry.target.id); }, { rootMargin: '-15% 0px -55% 0px', threshold: 0 });
    document.querySelectorAll('main section[id]').forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  return <><a href="#main" className="skip-link">Skip to content</a><header className="site-header"><nav className="container nav" aria-label="Main navigation"><a className="brand" href="#home" aria-label="Nicholas McCracken home"><Compass size={26} strokeWidth={1} /><span>NM<span className="brand-dot">.</span></span></a><div className="desktop-nav">{navigation.map(item=><a key={item} href={`#${item.toLowerCase()}`} aria-current={active===item.toLowerCase()?'location':undefined} className={active===item.toLowerCase()?'active':''}>{item}</a>)}</div><a className="nav-contact" href={profile.email}>Let’s connect <ArrowUpRight size={15}/></a><button className="menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{navigation.map(item=><a key={item} href={`#${item.toLowerCase()}`} onClick={()=>setMenu(false)}>{item}<ArrowUpRight size={16}/></a>)}</nav>}</header>
  <main id="main"><section className="hero container" id="home"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="status-dot"/> A LITTLE LOGIC. A LITTLE MAGIC.</div><h1>Nicholas<br/><span>McCracken</span><span className="name-period">.</span></h1><p className="hero-role">Software Engineer <span> / </span> AI/ML <span> / </span> Data Engineering</p><p className="hero-description">{profile.description}</p><p className="hero-tagline">{profile.tagline}</p><div className="hero-actions"><a className="button primary" href="#projects">View Projects <ArrowDown size={16}/></a><a className="button secondary" href={profile.resume} target="_blank" rel="noreferrer"><FileText size={16}/> Resume <ArrowUpRight size={14}/></a></div><div className="social-links"><a href={profile.github} target="_blank" rel="noreferrer"><Github size={16}/> GitHub <ArrowUpRight size={12}/></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={16}/> LinkedIn <ArrowUpRight size={12}/></a><a href={profile.email}><Mail size={16}/> Email <ArrowUpRight size={12}/></a></div></div><ArtifactDisplay/><div className="hero-bottom"><span><MapPin size={13}/> {profile.status}</span><a href="#experience">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>
  <section id="experience" className="section container"><SectionHeading number="01" title="Experience" subtitle="PAST ADVENTURES"/><div className="experience-intro"><p>Real-world challenges.<br/><span>Meaningful impact.</span></p><span className="section-note">A journey through intelligent systems,<br/>reliable infrastructure, and shared knowledge.</span></div><div className="timeline">{experiences.map((job,index)=><Reveal className="timeline-item" key={job.company+job.role}><div className="timeline-meta"><span className="timeline-marker">{index===0?<span/>:null}</span><p>{job.date}</p><span className="eyebrow">{job.kind}</span></div><div className="timeline-content"><h3>{job.company}</h3><p className="job-role">{job.role}</p><ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul></div></Reveal>)}</div></section>
  <section id="projects" className="section projects-section"><div className="container"><SectionHeading number="02" title="Selected projects" subtitle="ARTIFACTS I’VE BUILT"/><div className="projects-grid">{projects.map(project=><Reveal className="project-card" key={project.number}><div className="project-art-header"><span>ARTIFACT {project.number}</span><Compass size={17} strokeWidth={1}/></div><ProjectIllustration archive={project.motif==='archive'}/><div className="project-body"><span className="eyebrow">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-metric"><strong>{project.metric}</strong><span>{project.metricLabel}</span></div><div className="tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="project-footer">{project.github?<a href={project.github} target="_blank" rel="noreferrer"><Github size={15}/> View repository <ArrowUpRight size={15}/></a>:<button disabled title="Repository URL will be added soon"><Github size={15}/> Repository coming soon <ArrowUpRight size={15}/></button>}</div></div></Reveal>)}</div></div></section>
  <section id="skills" className="section container"><SectionHeading number="03" title="Skills" subtitle="TOOLS & DISCIPLINES"/><div className="skills-codex">{skills.map((category,index)=>{const Icon=[Code2,Network,Layers3][index];return <Reveal key={category.name} className="skill-row"><div className="skill-title"><span className="skill-icon"><Icon size={23} strokeWidth={1}/></span><div><h3>{category.name}</h3><p>{category.subtitle}</p></div></div><div className="tags skill-tags">{category.items.map(skill=><span key={skill}>{skill}</span>)}</div></Reveal>;})}</div></section>
  <section id="education" className="section container"><SectionHeading number="04" title="Education" subtitle="TRAINING & STUDY"/><Reveal className="education-panel"><div className="university"><GraduationCap size={32} strokeWidth={1}/><h3>The Ohio State<br/> University</h3><span><MapPin size={13}/> Columbus, Ohio</span><div className="gpa"><strong>3.9<span> / 4.0</span></strong><span>GPA</span></div></div><div className="degrees">{education.map((degree,index)=><div className="degree" key={degree.degree}><span className="eyebrow">{index===0?'GRADUATE STUDIES':'UNDERGRADUATE STUDIES'}</span><h4>{degree.degree}</h4><p>{degree.date}</p></div>)}</div></Reveal></section>
  <section id="contact" className="contact-section container"><div className="contact-orbit" aria-hidden="true"><Compass size={42} strokeWidth={0.65}/></div><span className="eyebrow">THE NEXT CHAPTER</span><h2>Want to build<br/>something <em>interesting?</em></h2><p>Interested in software engineering, AI/ML, data engineering,<br className="desktop-break"/> and ambitious technical projects.</p><a className="button primary" href={profile.email}>Let’s talk <Mail size={17}/></a><div className="contact-socials"><a href={profile.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><span>✧</span><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a></div></section></main><footer className="container footer"><a className="brand" href="#home"><Compass size={20} strokeWidth={1}/><span>NM.</span></a><p>© {new Date().getFullYear()} Nicholas McCracken</p><a href="#home">Back to the stars <ArrowRight size={14}/></a></footer></>;
}
