'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Github, Linkedin, Mail, FileText, Compass, Code2, Network, Layers3, GraduationCap, Menu, X, MapPin, Map } from 'lucide-react';
import { profile, navigation, experiences, projects, skills, education } from '@/lib/portfolio';
import ArtifactDisplay from './ArtifactDisplay';
import ProjectBanner from './ProjectBanner';
import CursorTrail from './CursorTrail';
function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={{ opacity: 1, y: reduced ? 0 : 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-35px' }} transition={{ duration: reduced ? 0 : 0.6 }}>{children}</motion.div>;
}
function SectionHeading({ number, title, subtitle }: { number: string; title: string; subtitle: string }) {
  return <div className="section-heading"><div><span className="eyebrow"><span className="chapter">{number}</span> {subtitle}</span><h2>{title}<span>.</span></h2></div><div className="heading-rule"><Map size={15} /></div></div>;
}
export default function Portfolio() {
  const [active, setActive] = useState('');
  const [menu, setMenu] = useState(false);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { for (const entry of entries) if (entry.isIntersecting) setActive(entry.target.id); }, { rootMargin: '-15% 0px -55% 0px', threshold: 0 });
    document.querySelectorAll('main section[id]').forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  return <><CursorTrail/><a href="#main" className="skip-link">Skip to content</a><header className="site-header"><nav className="container nav" aria-label="Main navigation"><a className="brand" href="#home" aria-label="Nicholas McCracken home"><Compass size={26} strokeWidth={1} /><span>NM<span className="brand-dot">.</span></span></a><div className="desktop-nav">{navigation.map(item=><a key={item} href={`#${item.toLowerCase()}`} aria-current={active===item.toLowerCase()?'location':undefined} className={active===item.toLowerCase()?'active':''}>{item}</a>)}</div><a className="nav-contact" href={profile.email}>Let’s connect <ArrowUpRight size={15}/></a><button className="menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{navigation.map(item=><a key={item} href={`#${item.toLowerCase()}`} onClick={()=>setMenu(false)}>{item}<ArrowUpRight size={16}/></a>)}</nav>}</header>
  <main id="main"><section className="hero container" id="home"><div className="hero-copy"><h1>Nicholas<br/><span>McCracken</span><span className="name-period">.</span></h1><p className="hero-role">AI/ML <span> / </span> Data <span> / </span> Software</p><p className="hero-description">{profile.description}</p><div className="hero-actions"><a className="button primary" href="#projects">View Projects <ArrowDown size={16}/></a><a className="button secondary" href={profile.resume} target="_blank" rel="noreferrer"><FileText size={16}/> Resume <ArrowUpRight size={14}/></a></div><div className="social-links"><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={16}/> LinkedIn <ArrowUpRight size={12}/></a><a href={profile.email}><Mail size={16}/> Email <ArrowUpRight size={12}/></a></div></div><ArtifactDisplay/><div className="hero-bottom"><span><MapPin size={13}/> {profile.status}</span><a href="#experience">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>
  <section tabIndex={-1} id="experience" className="section container"><SectionHeading number="01" title="Experience" subtitle="PAST ADVENTURES"/><div className="timeline">{experiences.map((job,index)=><Reveal className="timeline-item" key={job.company+job.role}><div className="timeline-meta"><span className="timeline-marker">{index===0?<span/>:null}</span><p>{job.date}</p><span className="eyebrow">{job.kind}</span></div><div className="timeline-content"><h3>{job.company}</h3><p className="job-role">{job.role}</p><ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul></div></Reveal>)}</div></section>
  <section tabIndex={-1} id="projects" className="section projects-section"><div className="container"><SectionHeading number="02" title="Projects" subtitle="ARTIFACTS I’VE BUILT"/><div className="projects-grid">{projects.map(project=><Reveal className="project-card" key={project.number}><div className="project-art-header"><span>ARTIFACT {project.number}</span><Compass size={17} strokeWidth={1}/></div><ProjectBanner motif={project.motif}/><div className="project-body"><span className="eyebrow">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-metric"><strong>{project.metric}</strong><span>{project.metricLabel}</span></div><div className="tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="project-footer">{project.report?<a href={project.report} target="_blank" rel="noreferrer"><FileText size={15}/> Read project report <ArrowUpRight size={15}/></a>:project.github?<a href={project.github} target="_blank" rel="noreferrer"><Github size={15}/> View repository <ArrowUpRight size={15}/></a>:<button disabled title="Repository URL will be added soon"><Github size={15}/> Repository coming soon <ArrowUpRight size={15}/></button>}</div></div></Reveal>)}</div></div></section>
  <section tabIndex={-1} id="skills" className="section container"><SectionHeading number="03" title="Skills" subtitle="TOOLS & DISCIPLINES"/><div className="skills-codex">{skills.map((category,index)=>{const Icon=[Code2,Network,Layers3][index];return <Reveal key={category.name} className="skill-row"><div className="skill-title"><span className="skill-icon"><Icon size={23} strokeWidth={1}/></span><div><h3>{category.name}</h3><p>{category.subtitle}</p></div></div><div className="tags skill-tags">{category.items.map(skill=><span key={skill}>{skill}</span>)}</div></Reveal>;})}</div></section>
  <section tabIndex={-1} id="education" className="section container"><SectionHeading number="04" title="Education" subtitle="TRAINING & STUDY"/><Reveal className="education-panel"><div className="university"><GraduationCap size={32} strokeWidth={1}/><h3>The Ohio State<br/> University</h3><span><MapPin size={13}/> Columbus, Ohio</span><div className="gpa"><strong>3.9<span> / 4.0</span></strong><span>GPA</span></div></div><div className="degrees">{education.map((degree,index)=><div className="degree" key={degree.degree}><span className="eyebrow">{index===0?'GRADUATE STUDIES':'UNDERGRADUATE STUDIES'}</span><h4>{degree.degree}</h4><p>{degree.date}</p></div>)}</div></Reveal></section>
  <section tabIndex={-1} id="contact" className="contact-section container"><div className="contact-orbit" aria-hidden="true"><Compass size={42} strokeWidth={0.65}/></div><h2>Let’s talk about<br/>the next <em>opportunity.</em></h2><p>Open to opportunities in AI/ML, data, and software engineering.<br className="desktop-break"/> Have a role in mind? I’d love to connect.</p><a className="button primary" href={profile.email}>Get in touch <Mail size={17}/></a><div className="contact-socials"><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a></div></section></main><footer className="container footer"><a className="brand" href="#home"><Compass size={20} strokeWidth={1}/><span>NM.</span></a><p>© {new Date().getFullYear()} Nicholas McCracken</p><a href="#home">Back to the map <ArrowRight size={14}/></a></footer></>;
}
